# Generated by Django 3.0.2 on 2020-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cdata', models.CharField(max_length=100)),
                ('cdiv', models.CharField(max_length=100)),
                ('ctype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNO', models.CharField(max_length=100)),
                ('realName', models.CharField(max_length=100)),
                ('className', models.CharField(max_length=100)),
                ('acID', models.CharField(max_length=100)),
                ('cfID', models.CharField(max_length=100)),
                ('vjID', models.CharField(max_length=100)),
                ('ncID', models.CharField(max_length=100)),
                ('acRating', models.IntegerField()),
                ('cfRating', models.IntegerField()),
                ('acTimes', models.IntegerField()),
                ('cfTimes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNO', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('cdate', models.CharField(max_length=100)),
                ('cdiv', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('newRating', models.IntegerField()),
                ('diff', models.IntegerField()),
            ],
        ),
    ]
