# Generated by Django 3.0.2 on 2020-01-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='cdata',
            new_name='cdate',
        ),
    ]
