# Generated by Django 3.0.2 on 2020-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0002_auto_20200127_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isActive',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='student',
            name='acID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='acRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='acTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='cfID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='cfRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='cfTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='ncID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='vjID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
