# Generated by Django 3.0.2 on 2020-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0003_auto_20200127_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='className',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='realName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuNO',
            field=models.CharField(default='', max_length=100),
        ),
    ]
