# Generated by Django 3.0.2 on 2020-01-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0004_auto_20200127_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='cid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentcontest',
            name='cid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='cdate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contest',
            name='cdiv',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='contest',
            name='cname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contest',
            name='ctype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcontest',
            name='diff',
            field=models.IntegerField(default=0),
        ),
    ]
