# Generated by Django 3.0.2 on 2020-01-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0005_auto_20200129_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='cnumber',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='studentcontest',
            name='className',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentcontest',
            name='realName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contest',
            name='cname',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='studentcontest',
            name='cname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='studentcontest',
            name='diff',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='studentcontest',
            name='ctype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
