# Generated by Django 3.0.2 on 2020-02-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0006_auto_20200129_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudentqueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNO', models.CharField(default='', max_length=100)),
                ('realName', models.CharField(default='', max_length=100)),
                ('className', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default='2019')),
                ('acID', models.CharField(blank=True, default='', max_length=100)),
                ('accheck', models.BooleanField()),
                ('cfID', models.CharField(blank=True, default='', max_length=100)),
                ('cfcheck', models.BooleanField()),
                ('vjID', models.CharField(blank=True, default='', max_length=100)),
                ('ncID', models.CharField(blank=True, default='', max_length=100)),
                ('execution', models.NullBooleanField()),
                ('execution_statu', models.BooleanField()),
            ],
        ),
        ]
