# Generated by Django 3.0.2 on 2020-01-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0006_auto_20200129_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontest',
            name='ctype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
