# Generated by Django 3.0.2 on 2020-02-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0007_auto_20200205_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentqueue',
            name='execution_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addstudentqueue',
            name='request_time',
            field=models.CharField(default='', max_length=100),
        ),

    ]
