# Generated by Django 3.0.2 on 2020-02-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0009_auto_20200205_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ncTimes',
            field=models.IntegerField(default=0),
        ),
    ]
