# Generated by Django 3.0.2 on 2020-02-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0011_studentcontest_solve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontest',
            name='solve',
            field=models.CharField(default='no data', max_length=100),
        ),
    ]
