# Generated by Django 3.0.2 on 2020-02-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0012_auto_20200208_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ncRating',
            field=models.IntegerField(default=0),
        ),
    ]
