# Generated by Django 3.0.2 on 2020-02-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0013_student_ncrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupstuID', models.TextField(default='')),
                ('studentNames', models.TextField(default='')),
            ],
        ),
    ]
