# Generated by Django 3.0.2 on 2020-02-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0014_studentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='remake',
            field=models.CharField(default='', max_length=100),
        ),
    ]
