# Generated by Django 3.0.2 on 2020-02-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0015_studentgroup_remake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='remake',
            new_name='remark',
        ),
    ]
