# Generated by Django 3.0.2 on 2020-02-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0018_auto_20200214_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNO', models.CharField(max_length=100)),
                ('realName', models.CharField(default='', max_length=100)),
                ('cid', models.IntegerField(default=0)),
                ('cname', models.CharField(max_length=1000)),
                ('cdiv', models.CharField(max_length=100)),
                ('subid', models.IntegerField(default=0)),
                ('code', models.TextField(default='')),
                ('tag', models.CharField(default='', max_length=200)),
                ('index', models.CharField(default='', max_length=200)),
                ('statu', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
