# Generated by Django 3.0.2 on 2020-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0020_cfcontest_ctime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestforecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(default='', max_length=100)),
                ('cname', models.CharField(default='', max_length=100)),
                ('starttime', models.IntegerField(default=0)),
                ('link', models.CharField(default='', max_length=1000)),
                ('during', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
