# Generated by Django 3.0.2 on 2020-02-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0022_auto_20200219_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcontest',
            name='endtimestamp',
        ),
        migrations.RemoveField(
            model_name='studentcontest',
            name='starttimestamp',
        ),
        migrations.AddField(
            model_name='contest',
            name='endtimestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='starttimestamp',
            field=models.IntegerField(default=0),
        ),
    ]
