# Generated by Django 3.0.2 on 2020-02-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0023_auto_20200219_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentqueue',
            name='school',
            field=models.CharField(default='北京化工大学', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='北京化工大学', max_length=100),
        ),
        migrations.AddField(
            model_name='studentcontest',
            name='aftersolve',
            field=models.CharField(default='no data', max_length=100),
        ),
    ]
