# Generated by Django 3.0.2 on 2020-02-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0024_auto_20200220_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='all_cf_aftersolve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='correct_cf_aftersolve',
            field=models.IntegerField(default=0),
        ),
    ]
