# Generated by Django 3.0.2 on 2020-02-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0026_auto_20200220_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestforecast',
            name='cid',
            field=models.IntegerField(default=0),
        ),
    ]
