# Generated by Django 3.0.2 on 2020-02-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0027_contestforecast_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestprize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('className', models.CharField(default='', max_length=100)),
                ('stuNO', models.IntegerField(default=0)),
                ('stuyear', models.IntegerField(default=0)),
                ('cname', models.CharField(default='', max_length=100)),
                ('cyear', models.IntegerField(default=0)),
                ('clevel', models.IntegerField(default=0)),
                ('prize', models.CharField(default='', max_length=100)),
                ('exe', models.BooleanField(default=False)),
            ],
        ),
    ]
