# Generated by Django 3.0.2 on 2020-02-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0028_contestprize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestprize',
            name='clevel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
