# Generated by Django 3.0.2 on 2020-02-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0029_auto_20200223_0908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contestprize',
            new_name='AddContestprize',
        ),
    ]
