# Generated by Django 3.0.2 on 2020-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0030_auto_20200223_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='cfstatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNO', models.CharField(default='', max_length=100)),
                ('realName', models.CharField(default='', max_length=100)),
                ('className', models.CharField(default='', max_length=100)),
                ('div1', models.IntegerField(default=0)),
                ('div2', models.IntegerField(default=0)),
                ('div3', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('cfRating', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('after', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
