# Generated by Django 3.0.2 on 2020-02-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0031_cfstatistics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cfstatistics',
            new_name='Weightrating',
        ),
    ]
