# Generated by Django 3.0.2 on 2020-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0032_auto_20200223_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightrating',
            name='acRating',
            field=models.IntegerField(default=0),
        ),
    ]
