# Generated by Django 3.0.2 on 2020-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmerdata', '0033_weightrating_acrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentqueue',
            name='atype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addstudentqueue',
            name='jskID',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addstudentqueue',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='jskID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='jskRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='jskTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='男', max_length=100),
        ),
        migrations.AlterField(
            model_name='addstudentqueue',
            name='cfID',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='addstudentqueue',
            name='className',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='addstudentqueue',
            name='realName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='addstudentqueue',
            name='school',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
    ]
